name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4 # Updated to v4 for latest features and security
      - name: Install, build, and upload your site
        uses: withastro/action@v2 # Updated to v2, the latest stable version
        with:
          path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 20 # Recommended to use a recent Node.js LTS version, e.g., 20 or 22 (optional)
          package-manager: npm # The Node package manager that should be used. Defaults to npm if not specified (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Updated to v4, the latest stable version